#Group Project FOGEL





```{r}
#| label: load-libraries
#| echo: false # This option disables the printing of code (only output is displayed).
#| message: false
#| warning: false

library(tidyverse)
library(wbstats) #World Bank Stat
library(skimr)
library(countrycode)
library(here)
library(scales)
library(ggtext)
library(viridis)



#| message: false
#| warning: false

# Download electricity data
url <- "https://nyc3.digitaloceanspaces.com/owid-public/data/energy/owid-energy-data.csv"

energy <- read_csv(url) %>% 
  filter(year >= 1990) %>% 
  drop_na(iso_code) %>% 
  select(1:3,
         biofuel = biofuel_electricity,
         coal = coal_electricity,
         gas = gas_electricity,
         hydro = hydro_electricity,
         nuclear = nuclear_electricity,
         oil = oil_electricity,
         other_renewable = other_renewable_exc_biofuel_electricity,
         solar = solar_electricity,
         wind = wind_electricity, 
         electricity_demand,
         electricity_generation,
         net_elec_imports,	# Net electricity imports, measured in terawatt-hours
         energy_per_capita,	# Primary energy consumption per capita, measured in kilowatt-hours	Calculated by Our World in Data based on BP Statistical Review of World Energy and EIA International Energy Data
         energy_per_gdp,	# Energy consumption per unit of GDP. This is measured in kilowatt-hours per 2011 international-$.
         per_capita_electricity, #	Electricity generation per capita, measured in kilowatt-hours
  ) 

# Download data for C02 emissions per capita https://data.worldbank.org/indicator/EN.ATM.CO2E.PC
co2_percap <- wb_data(country = "countries_only", 
                      indicator = "EN.ATM.CO2E.PC", 
                      start_date = 1990, 
                      end_date = 2022,
                      return_wide=FALSE) %>% 
  filter(!is.na(value)) %>% 
  #drop unwanted variables
  select(-c(unit, obs_status, footnote, last_updated)) %>% 
  rename(year = date,
         co2percap = value)


# Download data for GDP per capita  https://data.worldbank.org/indicator/NY.GDP.PCAP.PP.KD
gdp_percap <- wb_data(country = "countries_only", 
                      indicator = "NY.GDP.PCAP.PP.KD", 
                      start_date = 1990, 
                      end_date = 2022,
                      return_wide=FALSE) %>% 
  filter(!is.na(value)) %>% 
  #drop unwanted variables
  select(-c(unit, obs_status, footnote, last_updated)) %>% 
  rename(year = date,
         GDPpercap = value)
country_names <- energy_long %>% 
  distinct(iso_code, country) %>% 
  select(iso_code, country)

join1 <- gdp_percap %>% 
  left_join(co2_percap, by = c("country", "year")) %>% 
  select(iso_code = iso3c.x, country, year, GDPpercap, co2percap) %>% 
  left_join(country_names, by = "iso_code") %>% 
  rename(country = country.y)


join2 <- join1 %>% 
  left_join(energy, by = c("country", "year")) 


library(countrycode)
join2 <- join2 %>% 
  mutate(
    continent = countrycode(country, 
                            origin = 'country.name',
                            destination = "continent"),
    iso3c = countrycode(country, 
                        origin = 'country.name',
                        destination = "iso3c"),
  ) %>% 
  select(-c(iso_code.x, country.x, iso_code.y))


# Let us downlaod population data from World Bank
# https://data.worldbank.org/indicator/SP.POP.TOTL
# Download population data 
population <- wb_data(country = "countries_only", 
                      indicator = "SP.POP.TOTL", 
                      start_date = 1970, 
                      end_date = 2022,
                      return_wide=FALSE) %>% 
  filter(!is.na(value)) %>% 
  #drop unwanted variables
  select(-c(unit, obs_status, footnote, last_updated))

# join population data with everything else 
join2 <- join2 %>% 
  left_join(population, by=c("iso3c", "year"="date")) %>% 
  rename(population = value,
         country = country.x) %>% 
  select(-c(indicator_id, indicator, iso2c, country.y))

```





# Carbon Intensity of Electricity consumption

```{r}
library(reshape2)

energy_cols = c('biofuel','gas','coal','wind','solar','hydro','other_renewable', 'nuclear', 'oil')
id_cols= c('country','year','energy_per_capita','energy_per_gdp','per_capita_electricity','iso_code')

long_data <- pivot_longer(
  data = energy,
  cols = energy_cols,
  names_to = "energy_source",
  values_to = "value"
)
 
grouped <- long_data %>%
  group_by(year, country) %>%
  summarise(max_source= max(value))


  # Find the maximum value among the specified columns

  energy$max_value <- do.call(pmax, energy[,energy_cols])

# Find the column name corresponding to the maximum value
energy$main_source <- names(energy[, energy_cols])[max.col(energy[, energy_cols], "first")]

join3 <- join2
  join3$max_value <- do.call(pmax, join2[,energy_cols])
  join3$main_source <- names(join2[, energy_cols])[max.col(join2[, energy_cols], "first")]

class_colors <- c("hydro" = "blue", "nuclear" = "green", "biofuel"="yellow", "gas"="orange","solar"="grey", "wind"="purple","oil"="red","other_renewable"="pink","coal"="black")

library(ggrepel)
library(viridis)

# per capita kwh vs co2 per cap
co2_kwh_plot <- join3  %>% 
  drop_na(per_capita_electricity, main_source, co2percap) %>% 
  filter(year == 2020, 
         population > 10e6) %>% 
  ggplot()+
  aes(x=per_capita_electricity/365, y = co2percap, fill= main_source,
        size = population^2, 
      label = country,
      color= main_source ) +
  geom_point(alpha = 0.8)+  
  #scale_fill_manual(values = class_colors) + 
  scale_color_manual(values = class_colors)+
  labs(
    title = "Coal and gas remain the main energy sources in many energy-intensive countries",
    subtitle = "2019 kWh per capita, countries with population > 10m",
    x = "CO2 per capita emmissions",
    y = "kWh per capita per day"
  )+
  coord_flip()+
  theme_minimal()+
  geom_text_repel(size = 4)+
 # theme(legend.position = "none")+
  # scale_colour_viridis(discrete = T,
  #                      option = "D")+
  theme(
    plot.title.position = "plot",
    plot.title = element_textbox_simple(size=12),
    axis.text = element_text(size=9)
    ) +
  NULL   

co2_kwh_plot
```








